<?php

return [
    'menu' => [
        ['type' => 'link', 'label' => 'Tổng quan', 'route' => 'admin.dashboard', 'icon' => 'bi bi-speedometer2'],
        ['type' => 'header', 'label' => 'DU LỊCH'],
        ['type' => 'link', 'label' => 'Điểm đến', 'route' => 'admin.destinations.index', 'icon' => 'bi bi-geo-alt'],
        ['type' => 'link', 'label' => 'Loại hình tour', 'route' => 'admin.tour-categories.index', 'icon' => 'bi bi-diagram-3'],
        ['type' => 'link', 'label' => 'Danh mục dịch vụ', 'route' => 'admin.service-categories.index', 'icon' => 'bi bi-grid-3x3-gap'],
        ['type' => 'link', 'label' => 'Dịch vụ', 'route' => 'admin.services.index', 'icon' => 'bi bi-signpost-2'],
        ['type' => 'link', 'label' => 'Tour du lịch', 'route' => 'admin.tours.index', 'icon' => 'bi bi-map'],
        ['type' => 'link', 'label' => 'Khoảnh khắc', 'route' => 'admin.travel-moments.index', 'icon' => 'bi bi-images'],
        ['type' => 'header', 'label' => 'ĐẶT TOUR'],
        ['type' => 'link', 'label' => 'Booking', 'route' => 'admin.bookings.index', 'icon' => 'bi bi-calendar-check'],
        ['type' => 'link', 'label' => 'Ưu đãi', 'route' => 'admin.promotions.index', 'icon' => 'bi bi-tags'],
        ['type' => 'link', 'label' => 'Mã giảm giá', 'route' => 'admin.coupons.index', 'icon' => 'bi bi-ticket-perforated'],
        ['type' => 'header', 'label' => 'NỘI DUNG'],
        ['type' => 'link', 'label' => 'Trang giới thiệu', 'route' => 'admin.about.edit', 'icon' => 'bi bi-info-circle'],
        ['type' => 'link', 'label' => 'Trang tĩnh', 'route' => 'admin.pages.index', 'icon' => 'bi bi-file-earmark-richtext'],
        ['type' => 'link', 'label' => 'Danh mục bài viết', 'route' => 'admin.post-categories.index', 'icon' => 'bi bi-folder2-open'],
        ['type' => 'link', 'label' => 'Bài viết', 'route' => 'admin.posts.index', 'icon' => 'bi bi-newspaper'],
        ['type' => 'link', 'label' => 'Slider trang chủ', 'route' => 'admin.sliders.index', 'icon' => 'bi bi-images'],
        ['type' => 'link', 'label' => 'Cảm nhận khách hàng', 'route' => 'admin.testimonials.index', 'icon' => 'bi bi-chat-quote'],
        ['type' => 'link', 'label' => 'Menu website', 'route' => 'admin.menus.index', 'icon' => 'bi bi-menu-button-wide'],
        ['type' => 'link', 'label' => 'Yêu cầu liên hệ', 'route' => 'admin.contact-submissions.index', 'icon' => 'bi bi-inbox'],
        ['type' => 'header', 'label' => 'HỆ THỐNG'],
        ['type' => 'link', 'label' => 'Tài khoản admin', 'route' => 'admin.users.index', 'icon' => 'bi bi-shield-lock'],
        ['type' => 'link', 'label' => 'Phân quyền', 'route' => 'admin.roles.index', 'icon' => 'bi bi-person-gear'],
        ['type' => 'link', 'label' => 'Cài đặt', 'route' => 'admin.settings.index', 'icon' => 'bi bi-gear'],
    ],
];
